config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'sources#index'
  get '/update', to: 'sources#update'
  resources :sources

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :source
end

app/models/source.rb
class Source < ActiveRecord::Base
  belongs_to :user
  has_many :articles, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sources, dependent: :destroy
  has_many :articles, through: :sources
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  helper_method :get_source_timer

  def index
    @articles = current_user.articles.order(pub_date: :DESC).page(params[:page]).per(12)
  end

  def new
    @source = current_user.sources.new
  end

  def update
    current_user.sources.all.each do |source|
      clear_articles(source)
      ParseRss.new(current_user).get_articles(source)
    end
    redirect_to sources_path
  end

  def create
    @source = current_user.sources.new(source_url)
    if current_user.sources.find_by(source_url)
      flash[:alert] = "Error :  #{source_url[:url]} already added"
    elsif current_user.sources.count > 24
      flash[:alert] = "Error :  You have reached the fair use of 25 RSS feeds"
    else
      #begin
        clear_url(@source.url)
        rss = ParseRss.new(current_user).get_rss(@source)
        @source.name = @source.url
        get_source_name(@source.name)
      #rescue
        #flash[:alert] = "Network error : #{source_url[:url]} count not be reached"
      #end
      if rss
        @source.save
        flash[:notice] = "#{@source.name} added"
        begin
          ParseRss.new(current_user).get_articles(@source)
        rescue
          flash[:alert] = "Error when trying to save articles from  #{source_url[:url]}"
        end
      end
    end
    redirect_to sources_path
  end

  def destroy
    get_source
    if @source.destroy
      flash[:notice] = "#{@source.name} successfully deleted"
    else
      flash[:alert] = "Error : #{@source.name} not deleted"
    end
    redirect_to root_path
  end

  private

  def source_url
    params.require(:source).permit(:url, :source_id)
  end

  def get_source
    @source = current_user.sources.find(params[:id])
  end

  def clear_articles(source_id)
    source_id.articles.destroy_all
  end

  def get_source_name(url)
    url.slice!("/feed/")
    url.slice!("/feed")
    url.slice!("feed/")
    url.slice!("www.")
    url.slice!("www2.")
    url.slice!("page=")
    url.slice!("backend")
    url.slice!("spip")
    url.slice!(".php")
    url.slice!("?")
    url.slice!("=")
  end

  def clear_url(url)
    url.slice!("http://")
    url.slice!("https://")
  end

  def get_source_timer(article)
    now = DateTime.now
    pubdate = DateTime.parse(article.pub_date.to_s)
    time = (now - pubdate).to_f * 24
    if time == 0
      day = "Just now"
    elsif time < 24
      day = time.round.to_s + " hours"
    else  time >= 24
      day = " Yesterday"
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>SheebyRSS</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container-fluid">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="notice alert alert-info" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="notice alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse sticky-top">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">Sheeby RSS</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item mr-2 mb-1">
          <%= link_to icon("")+"Add "+icon("rss")  , new_source_path, :class => 'btn-outline-info btn'  %>
        </li>
        <li class="nav-item">
          <%= link_to icon("refresh")+" Update"  , "/update", :class => 'btn-outline-success btn'  %>
        </li>
      <% end %>
    </ul>

    <ul class="navbar-nav my-2 my-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item  mr-2 mb-1">
          <%= link_to icon("user-circle-o") + " " + current_user.email , edit_user_registration_path, :class => 'btn-outline-secondary btn' %>
        </li>
        <li class="nav-item">
          <%= link_to icon("sign-out") + "Logout", destroy_user_session_path, method: :delete, :class => 'btn-outline-danger btn'  %>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/sources/index.html.erb
<div class="card-columns">
  <% @articles.each do |article| %>

      <div class="card ">
        <div class="card-block">
          <button type="button" class="close" aria-label="Close">
            <span aria-hidden="true">
              <%= link_to icon('close', class: "text-danger") , article.source ,
                method: :delete,
                data: { confirm: "Are you sure to delete this source ?" } %>
            </span>
          </button>
          <a href="<%= article.url %>" class="card-title">
            <h4><%= article.title %></h4>
          </a>
          <p class="card-text"><%= article.excerpt %></p>
          <div class="d-flex justify-content-between">
              <small class="text-muted"><%= icon("clock-o") +  get_source_timer(article) %></small>
              <small class="text-primary"><%= icon("globe") + " " + article.source.name %></small>
          </div>
        </div>
      </div>

  <% end %>
</div>

<% unless @articles.current_page == @articles.total_pages %>
  <p id="view-more">
    <%= link_to('View More', url_for(page: @articles.current_page + 1), class: "btn btn-primary btn-block") %>
  </p>
<% end %>

app/views/sources/new.html.erb
<%= simple_form_for @source  do |f| %>
  <%= f.input :url , label: false, placeholder: "sheebypanda.com/feed/" %>
  <%= f.button :submit %>
<% end %>